
# The Ross-Macdonald Model

The development of the Ross-Macdonald model has been discussed elsewhere [@SmithDL2012_RossMacdonald]. There is not a single paper where a system of equations was published by Macdonald. Instead, the model traces back to several different publications that present equations and formulas describing malaria transmission. We have already mentioned that Ronald Ross published two models of malaria transmission, but we also owe a lot to Alfred Lotka, who analyzed both models.  

Ross's first model described malaria transmission dynamics using  difference equations [@RossR1908]. That model was reviewed, analyzed, and critiqued first by H. Waite in 1910,  [@WaiteH1910MosquitoesMalaria]. The formulation is a bit hard to follow, so we will present a system of difference equations in place of the equations Ross actually wrote down. 

**Lotka**

Ross's second model was thoroughly analyzed by Lotka, who had taken an active interest in Ross's malaria models. In 1912, he published a set of solutions to Ross's equations [@LotkaAJ1912Nature]. In 1923, Lotka published an analysis of both of Ross's models in five parts. The first two parts reformulate Ross's models [@LotkaAJ1923part1;@LotkaAJ1923part2]. The third part tackles numerical issues, which includes a photograph of a clay model of the phase plane as a surface [@LotkaAJ1923part3], and the fifth part is a concise summary [@LotkaAJ1923part5]. In the $4^{th}$, which was led by Sharpe, a new model was introduced that included delays for the latent periods [@LotkaAJ1923part4].    

**Macdonaald** 


Macdonald made several important contributions to the mathematical study of malaria. Ross's original formulation remained the standard until Macdonald's paper on the sporozoite rate [@MacdonaldG1952Sporozoite]. Because of it's historical interest, we'll discuss Ross's formulation in the discussion of [Macdonald's Model], in part, to make it clear why Macdonald's contribution was significant enough to get his name attached.

In the 1950s, George Macdonald published a set of papers describing malaria transmission dynamics and control, culminating in publicataion of a book _The Epidemiology and Control of Malaria_ [@MacdonaldG1957Book]. 
<!-- An important caveat is that Macdonald relied on the mathematical talents of Armitage for the equations describing superinfection and the sporozoite rate [@ArmitageP1953].  -->

In 1950, Macdonald published a new model with human malaria superinfection [@MacdonaldG1950Superinfection] and a synthetic review of malaria epidemiology [@MacdonaldG1950Epidemiology].  In 1952, Macdonald published a synthetic review of medical entomology [@MacdonaldG1952Sporozoite] and introduced the concept of a basic reproductive number, $R_0$ [@MacdonaldG1952R0].  
    
As a side note, it's highly likely that Macdonald was aware of Lotka's demographic concept of $R_0$, as well as his work with Sharpe on delay differential equations [@LotkaAJ1923part4], though we have been unable to find a single line where Macdonald gives Lotka the credit. For these reasons, and others, the equations ought to be described as the Ross-Lotka-Macdonald model.  

## Difference Equations 

Ross had measured malaria prevalence in different populations, and he knew that the level of prevalence was related to mosquito populations. He recognized that prevalence could change, and that what set its value was a balance between two processes. 

The logic looks like this: 

$$
\left[
\begin{array}{rcl}
\mbox{Fraction Infected Today} &=& \mbox{Fraction Infected Yesterday} \;\; -\\
&& \mbox{Cleared Infections} \;\; + \\
&& \mbox{Fraction Uninfected that Got Infected}\\
\end{array} \right]
$$
This description ignores infected people who died, infected people who emigrated, and infected people who immigrated. It's not perfect, but it's a starting point. 

For mosquitoes, we assume they are much more likely to die than to clear infections.  
So we the process is slightly different: 

$$
\left[
\begin{array}{rcl}
\mbox{Fraction Infected Today} &=& \mbox{Fraction Infected that Survived} \;\; -\\
&& \mbox{Fraction Uninfected that Got Infected}\\
\end{array} \right]
$$
What's important here is that infectious mosquitoes are infecting people when they bite, and infectious people are infecting mosquitoes when the mosquito blood feeds. This process is clarified by a diagram: 

**Model** 

We can translate this description into a model, but we need to start speaking math.  

*Variables:* 

+ Let $x_t$ be the fraction of people who are infected at time $t$

+ Let $y_t$ be the fraction of mosquitoes who are infected at time $t$

**Parameters** 

+ Let $s$ denote the fraction of people who remain infected after one day 

+ Let $p$ denote the fraction of mosquitoes who remain alive after one day. 

+ Let $a$ denote the fraction of mosquitoes who blood feed on a human 

+ Let $m$ denote the number of mosquitoes per human 

**Equations** 

$$\begin{array}{rl}
x_{t+1} &=  m a y_t (1-x_t) + s x_t \\ 
y_{t+1} &=  a x_t (1 - y_t) + p y_t\\ 
\end{array}$$

This is one good place to start.

## Differential Equations 

The second was formulated as a system of two ordinary differential equations, in the $2^{nd}$ edition of _The Prevention of Malaria_ [@RossR1911Book]. Ross also published the same model in _Nature_ [@RossR1911Nature] in this form: 

$$ 
\begin{array}{rl}
dz/dt &= k' z' (p-z) + q z \\
dz'/dt &= k z (p'-z') + q' z' \\
\end{array}
$$ 
At the time, there was not much evidence from malaria research to frame the problem. A fully parameterized model, using biologically meaningful parameters, would have to wait for a few decades of research and a synthesis by Macdonald.

If we change a few variable and parameter names (let $z=x$, $z'=y$, $k' = ma$, $k=a$, $r=e^{-s}$, and $p=e^{-g}$), we get something that looks like the other equations: 
$$ 
\begin{array}{rl}
dx/dt &= may(1-z) - r x\\
dy/dt &= ax(1-y) - g z \\
\end{array}
$$ 
This equation lacks an infective state for mosquitoes. 


## Macdonald's Model 

The following is a candidate for what the Ross-Macdonald model might have looked like, if Macdonald had ever written it down. 

### Variables

The model has two variables:

+ $x$ is the fraction of humans who are infected; 

+ $y$ is the fraction of adult female mosquitoes who are infected.  

+ $z$ is the fraction of adult female mosquitoes who are infective.  

### Parameters

The model has several parameters: 

+ $g$: mosquitoes die at a constant rate, $g$. This is equivalent to assuming that the mosquito lifespan is exponentially distributed with a mean $1/g$. Macdonald's equation use $p$, the fraction surviving one day, $p = e^{-g}$. 

+ $\tau$: it takes $\tau$ days for parasites to mature and reach the salivary glands, called the EIP.  The fraction surviving the EIP is $p^\tau = e^{-g \tau}$. 

+ $m$: there are $m$ mosquitoes per human;

+ $a$: mosquitoes blood feed on humans at the rate $a$; 

+ $b$: a fraction of bites by *infectious* mosquitoes causes an infection; 

+ $r$: human malaria infections clear at the rate $r$;  

+ $c$: a fraction of bites on infected humans infect a mosquito, denoted $c$


### Dynamics 

In this formulation of the model, we ignore the delay for the EIP but we count the mortality: 

$$ 
\begin{array}{rl}
dx/dt &= b m a z (1-x) - r x \\
dy/dt &= c a x (1-y) - g y  \\
dz/dt &= e^{-g \tau} c a x_\tau (1-y_\tau) - g z  \\
\end{array}
$$   

this. 

## The Basic Reproductive Number 

## Sensitivity to Parameters 

## The Classification of Transmission 

## History

### Alfred J. Lotka 

+ While Alfred J. Lotka is more famous for his work in demography and ecology, he took an interest in Ross's work on malaria and he made some important contributions to mathematical malaria epidemiology: 

 
    
- Most importantly, Lotka developed the concept of the basic reproductive number in his work in human demography, which was defined as the expected number of females that would be born to a newborn female. 

### George Macdonald  


we'll discuss Ross's actual formulation,
