# Basic Models 

Ross was interested in what caused differences in malaria prevalence. 

He attributed to differences in exposure to infectious mosquitoes. He knew that the level of prevalence was related to local mosquito populations, but he also recognized that malaria could be acquired elsewhere (*e.g.* while traveling). 
He recognized that prevalence could change, and that what set its value was a balance between two processes. The quantitative logic looks like this: 

$$
\left[
\begin{array}{rcl}
\mbox{Fraction Infected Today} &=& \mbox{Fraction Infected Yesterday} \;\; \\
&& \mbox{Cleared Infections} \;\; + \\
&& \mbox{Fraction Uninfected that Got Infected}\\
\end{array} \right]
$$

This description ignores infected people who died, infected people who emigrated, and infected people who immigrated. The model is neither comprehensive nor perfect. It was a starting point. 

For short-lived mosquitoes, we assume they are much more likely to die than to clear infections. So for mosquitoes, the process is slightly different: 

$$
\left[
\begin{array}{rcl}
\mbox{Fraction Infected Today} &=& \mbox{Fraction Infected Today} \\
&-&\mbox{Fraction of Infected Mosquitoes that Died}\\
&+& \mbox{Fraction of Uninfected Mosquitoes that Got Infected}\\
\end{array} \right]
$$

What's important here is that infectious mosquitoes are infecting people when they bite, and infectious people are infecting mosquitoes when the mosquito blood feeds. This process is clarified by a diagram: 

In the following, we will write down four distinct mathematical equations that follow these basic rules: 

1. As a deterministic system in discrete time; 

2. As a stochastic system in discrete time;  

3. As a deterministic system in continuous time; 

4. A simulation model in continuous time. 

## Discrete Time, Deterministic

We can translate this description into a model, but we need to start speaking math. The parts of a model are 

*Variables:* 

+ Let $x_t$ be the fraction of people who are infected at time $t$

+ Let $y_t$ be the fraction of mosquitoes who are infected at time $t$

*Parameters* 

+ Let $s$ denote the fraction of people who remain infected after one day 

+ Let $p$ denote the fraction of mosquitoes who remain alive after one day. 

+ Let $a$ denote the fraction of mosquitoes who blood feed on a human 

+ Let $m$ denote the number of mosquitoes per human 

*Equations* 

$$\begin{array}{rl}
x_{t+1} &=  m a y_t (1-x_t) + s x_t \\ 
y_{t+1} &=  a x_t (1 - y_t) + p y_t\\ 
\end{array}$$

This is one good place to start.

## Continuous Time, Deterministic

The second was formulated as a system of two ordinary differential equations, in the $2^{nd}$ edition of _The Prevention of Malaria_ [@RossR1911Book]. Ross also published the same model in _Nature_ [@RossR1911Nature] in this form: 

$$ 
\begin{array}{rl}
dz/dt &= k' z' (p-z) + q z \\
dz'/dt &= k z (p'-z') + q' z' \\
\end{array}
$$ 
At the time, there was not much evidence from malaria research to frame the problem. A fully parameterized model, using biologically meaningful parameters, would have to wait for a few decades of research and a synthesis by Macdonald.

If we change a few variable and parameter names (let $z=x$, $z'=y$, $k' = ma$, $k=a$, $r=e^{-s}$, and $p=e^{-g}$), we get something that looks like the other equations: 
$$ 
\begin{array}{rl}
dx/dt &= may(1-z) - r x\\
dy/dt &= ax(1-y) - g z \\
\end{array}
$$ 
This equation lacks an infective state for mosquitoes. 

## Discrete Time, Stochastic 

## Continuous Time, Stochastic 

### Deterministic  

### Stochastic  

We want to to introduce a mathematical model that is a good starting point. None of the models presented in the previous chapter are suitable, largely because the variables in those models were proportions. The models we will use are almost identical, but the variables are densities. 

*** 

The Ross-Macdonald model is useful as a concise way of understanding malaria transmsission through the parasite's life-cycle. There is, however, a great deal of complexity that the Ross-Macdonald model does can not address, and some of it matters a great deal in policy. We must extend the model using new mathematical constructs to deal with several features of malaria: 

+ malaria immunity and disease in cohorts of humans as they age; 

+ human demography; 

+ anti-malaria drugs and other pharmaceutical interventions; 

+ heterogeneous exposure

+ spatial dynamics and malaria importation; 

+ mosquito ecology and behavior; 

+ exogenous forcing by weather, giving rise to seasonal and unstable dynamics;  

+ and vector control. 

In the following chapters, we will introduce and critically review the models that have been developed to address these topics in some detail. As we take on these new features and add complexity, we will (in effect) be going around the parasite and mosquito life-cycles over and over again, each time pursuing a new theme. 

We want to pursue the idea of scaling complexity in dynamic models ranging from simple and abstract to highly realistic. We want to arrive at a happy compromise -- a model that is "as simple as possible, but no simpler." (This is often attributed to Einstein, who probably  never said it that way exactly [@RobinsonA2018DidEinstein]). It might be hard to convince anyone that a model of intermediate complexity is good enough unless at least _some_ of the models have clearly gone too far. We don't want to add new features to our models unless they would affect some important aspect of malaria transmission dynamics and control.

Ideally, we would let the data tell us about the right level of complexity, but how would we ever convince someone to collect the data we need? If we don't expect to be able to collect all the data, we can do some of the hard work up front to set some prioritize.
One way to pursue questions about what details are likely to be biologically relevant is through model building and model-model comparison. If we can't identify a case where knowing something would change our policies using a mathematical model, it's probably not worth collecting the data for policy. We think of all these models as crude approximations to a messy reality -- the question we want to address is whether the approximations are good enough to use as a basis for giving policy advice. Building very complex models that are also mathematically and biologically sound and meaningful is a daunting task, but we have developed a modular system for building models that streamlines the model building process. 

To get started, we will reintroduce the Ross-Macdonald model in a form that is easier to extend than the one Macdonald made famous [@SmithDL2012_RossMacdonald]. We will start with a model that first appeared in  a 1982 book chapter written by Joan Aron and Robert May [@AronJL1982PopulationDynamics]. It is a good starting point because it is *extensible.* 

We chose it because the variables represent population densities, which are used to compute proportions, like *prevalence.* In the version of the Ross-Macdonald we presented before (in [Rebuilding Macdonald's Model]), the variables are proportions. In some models, we would like the *total* number of hosts to change over space or time, but if our state variables are proportions, then these densities appear in the denominators, which would make them much more difficult to modify. By writing down equations using densities, it is far easier to add complexity. 


*** 
**Why use densities?** 

To show why we use densities, we present a simple example. If we write down an equation describing changes in the density of infected humans, $X$, in a population with total human population density $H$. We let $V$ denote vectorial capacity, and $b$ the fraction of infective bites that cause an infection, and we assume the force of infection is $bVX/H$. The dynamics of infection are described by this simple equation:  

$$\frac{dX}{dt} = bV\frac{X}{H}(H-X)-rX$$ 
In this equation, prevalence is $x = X/H.$ Following through with the change in variables, we can write down the equation for the change in prevalence: 

$$\frac{dx}{dt} = \frac{1}{H^2} \left(H \frac{dX}{dt} - X \frac{dH}{dt} \right)$$

and with some rearranging, we get:

$$\frac{dx}{dt} = bVx(1-x)-rx -x \frac{dH}{dt}$$ 

The second equation is as simple as the first only if $dH/dt=0$. Since we will want to deal with dynamical changes in host populations, we will avoid formulating base models that have proportions. 

*** 

The model is extensible because, as we will see, mosquito population density is a variable, not a term. A parameter in the equation describing changes in mosquito density provides a link to aquatic mosquito ecology, which makes it possible to develop models for mosquito population dynamics, when that is an important consideration. In this version, we find that the formulas describing $R_0$ and vectorial capacity tell the story of parasite transmission through two blood meals. We will thus update the classical formulas. While Macdonald's analysis and formulas are familiar to many, they were incomplete [@SmithDL2004Statics; @SmithDL2021OldMosquitoes]. We develop a formula for vectorial capacity that is consistent with the intent of the original, but our analysis of sensitivity to parameters includes effects on mosquito ecology [@BradyOJ2015AdultVector]. (A lengthy and philosophical discussion of the history and its failings is planned.) 

We chose it because it is *realistic.* Time does not appear in most versions of the Ross-Macdonald model: the equations are *autonomous*. These equations use time to drive a seasonal pattern: they are *non-autonomous*. Since we know we are interested in dealing with exogenous forcing, we start out with a model that is forced.  

While the following model is basic, we recommend reading it, if only because we introduce concepts and conventions that are important for the software design.

## Historical Notes 

If we were simply learning the math, ...

When we analyze these equations to determine their *stability* and to identify *threshold conditions,* we focus on threshold conditions and the behavior of these systems when malaria is rare. In most places, malaria is endemic so we need to be concerned about malaria immunity and its effects on transmission; malaria is under some level of control; and because of weather and other factors, the baseline conditions change from year to year. 



