# Realism & Pragmatism

There are several reasons why models for policy will tend to be more complex than models developed for science.
In science, the questions are narrow and the study designs are focused enough to form tests of ideas that have clear outcomes.
When models are used to guide policy, the same level of scientific rigor should be applied, but weighing all the evidence requires a broder synthesis.  
To build models that can guide malaria policies, the models must be *realistic* enough to be compelling, and they *ought* to reflect the knowledge and experience accumulated over years of studying and controlling malaria. 
Policy advice should be checked for consistency across studies. 
The models must be complex enough to serve many purposes all at once. 
To weigh tradeoffs, policy requires broad, synthetic models that allow for comparisons across subject matter domains.


To carry a conversation forward, the models used to guide discussions will need to retain a memory of what has been learned already, so they will tend to add features and grow more complex.
Given the uncertainty, policy should be based on model swarms that propagate the uncertainty.
The predictions of those models must be specific enough to be proven wrong, so that over time *some* of the models can be trusted over others.
The same models can be used to identify which missing data would have the greatest impact on a policy, and ideally, studies can be conducted to gather this data.
Over time, the advice should shift from *generic* advice to *specific* advice as more evidence is gathered. 
This is, in a nutshell, how daptive management works.

It might take a lot of work to build a model that has been fit to all the evidence describing malaria in a management unit over the recent past, and it might cut against the instincts we have as scientists to add all that realism, but it's worth it to make the effort if it helps communicate with malaria managers. 

*** 

In designing a software solution to the problem of building realistic models, we designed a framework for building models and a toolbox to build model swarms that would address the concerns of malaria programs. In the chapters that follow, we'll show the features of this framework by constructing examples. Even if we're principled about adding complexity, a cost of doing so is *computational complexity.* That is something the software was designed to manage. For the moment, we thus want to set aside concerns about *realism* vs. *abstraction*, about *parsimony*, and about *error propagation,* and we want to simply ask the question of how to build models with the features we want. 

This chapter is an overview of the historical development of malaria models and an introduction to the toolbox. We'll cover the same material in much greater detail in the chapters that follow, and we'll construct examples using `exDE` and `MicroMoB`. 

## Epidemiology

A major challenge for malaria dynamics is how to define an state space describing malaria infection and immunity in human populations that captures the essential elements of malaria dynamics -- good enough to trust for making policies. There are features of malaria infections that have been identified and studied in the past: superinfection; the complex time course of an infection -- including fluctuating parasite densities -- and the problem of detection; gametogenesis, gametocyte maturation and gametocyte dynamics; fever and disease; development of immunity with exposure including its effects on infection, disease, and infectiousness; treatment, adherence to drug regimens, chemoprotection and infection curing. Over time, these issues have been addressed in various models. We need model that is good enough for policy, but this also means developing a commmon understanding of malaria that can serve as a basis for discussion.  

To get to that point, we must start simple and add complexity. 

The model for malaria infection that we presented in [Malaria Dynamics] was developed by Ross. In today's vernacular, it would be called an SIS compartment model. The model is very simple, and it is probably inadequate for every task, but it is useful and it has been used. The model assumes that malaria infections clear at a constant rate regardless of the age of infection or other factors. The persistence of malaria infections over decades tells us that this assumption is clearly false, but it is good enough for some programmatic needs. During the GMEP, Ross's model was used to characterized the response timelines for the *Pf*PR after the interruption of transmission. Drawing on multiple sources, Macdonald estimated that the duration of infection was around 200 days, which was good enough to use as a basis for monitoring and evaluating the interruption of transmission  [@MacdonaldG1964MalariaParasite]. The simpler model was used even though Macdonald had already proposed an alternative model that considered superinfection [@MacdonaldG1950_Superinfection]. Despite the simplicity, the model was adequate to the task [@SmithDL2009EndemicityResponse]. An important lesson is that the simplicity has some advantages, and the models that get used in policy tend to be very simple. 

The question is how to develop models that are simple and yet are up to policy tasks, which means that the models must (at some point) get validated against research data. Doing so means having sufficient complexity to deal with exposure, infection, detection, immunity, disease, infectiousness, care seeking, and drug taking. Whatever model is selected as a basis for policy, it should be simple enough to understand and yet complex enough to capture the *gist* of malaria epidemiology. The models, however chosen, must get it right. Sorting through all the complexity to get a model that is good enough is a daunting task. This introduction is mainly historical, but we use it to preview some of the themes. In the following history, we discuss some of the important innovations. 

### Superinfection 

From early on in malaria epidemiology it was clear that exposure to malaria differed among populations, and that in some places, the rate of exposure was far higher than the rate of clearance. Ross emphasized a need to measure exposure both entomologically, through metrics that are known today as the EIR and the FoI, and parasitologically, through the prevalence of infection by light microscopy (or more commonly today, through RDTs), which was called the malaria *parasite rate* . There was no good reason to believe that people in highly malarious areas would be exposed faster than they would clear infections, so they would carry infections that could be traced back to many infectious mosquitoes [@WaltonG1947ControlMalaria]. This phenomenon was called superinfection.

Macdonald was the first to develop a mechanistic model of superinfection [@MacdonaldG1950_Superinfection], but the mathematical formulation was at odds with his description [@FinePEM1975SuperinfectionProblem]. It is an interesting bit of history for a different time. 

A mathematical basis for understanding superinfection was worked out as a problem in the study of stochastic processes as part of *queueing theory.* This may seem strange, but understanding how many people are queueing involves understanding how people come in and how fast they are processed. One of these queuing models has become a mainstay of malaria epidemiology; in queuing theory, it is called $M/M/\infty$. 

The model tracks the **multiplicity of infection** (MoI). It assumes that infections arrive through exposure at a rate $h$ (the FoI), and that they clear independently. Without clearance, the MoI, denoted $\zeta$, would just go up. The model assumes that each infection clears at the rate $r$; if the MoI were $3$ then infections would clear at the rate $3r$. Regardless of how fast infections arrive, the fact that the pressure for the MOI to go down increases with MoI means that the MoI will reach a stable state. The mean MoI is $h/r.$ The following diagram illustrates and provides the equations: 

\begin{equation*}
\begin{array}{c}
%
\begin{array}{ccccccccc}
\zeta_0 &  {h\atop \longrightarrow} \atop {\longleftarrow \atop r} & \zeta_1  & {h\atop \longrightarrow} \atop {\longleftarrow \atop {2r}} & \zeta_2  & {h \atop \longrightarrow} \atop {\longleftarrow \atop {3r}} & \zeta_3  & {h \atop \longrightarrow} \atop {\longleftarrow \atop {4r}}& \ldots 
\end{array} 
\\ 
\\ 
\begin{array}{rl}
d\zeta_0/dt &= -h \zeta_0 + r \zeta_1 \\ 
d \zeta_i /dt &= -(h+r) \zeta_i + h \zeta_{i-1} + r(i+1) \zeta_{i+1} \\
\end{array} 
\end{array}
\end{equation*}

If one is willing to abandon compartment models, then it is possible to formulate more elegant solution using hybrid models. The mean MoI, $m$ changes according to the equation:

$$\frac{dm}{dt} = h - r m.$$
Using queuing models, it is easy to show that the distribution of the MoI is Poisson, and in these hybrid models, if the initial distribution is not Poisson, then it will converge to the Poisson distribution asymptotically. The complex dynamics of superinfection can thus be reduced to this simple equation.

Unfortunately, things become more complex if we add simple features such as treatment with drugs, or heterogeneous exposure. The distribution of the MoI is no longer Poisson [@HenryJM2020HybridModel]. Superinfection is an important part of malaria epidemiology, and we will use these models for superinfection in developing some adequate models for infection and immunity. 

In the Garki Model (see below), the waiting time to clear an infection used these queuing models to formulate an approximate clearance rate: $$ \frac{h}{e^{h/r}-1}$$

### Infection and Immunity 

The biggest failing of Ross's model, perhaps, was that it did not make any attempt to grapple with acquired immunity to malaria. It had always been clear that immunity to malaria was important because the prevalence of infection declined throughout adolescence and was consistently lower in adults, and because disease and severe disease were common in young children. The data accumulated through years of studying malaria, done as part of malaria therapy, provided supporting evidence for immunity. There was a difference in outcomes from being exposed to the same parasite (homologous challenge) compared with a different parasite (a heterologous challenge). Immunity had something to do with the number of different parasites that a person had seen. 

The first model to grapple with immunity was the Garki Model [@DietzK1974MalariaModel]. The main idea in the Garki Model was that it would be possible to understand malaria dynamics by expanding the number of compartments: the population was sub-divided into two non-immmune or semi-immune. Infection dynamics were tracked separately within each immune category: the infections would clear faster from semi-immune individuals, they were are not infectious, and they are less likely to test positive if they were infectious. Some features of the Garki model seem odd in retrospect: there were two infected states for non-immunes ($y_1$ and $y_2$), but only one for semi-immunes; there was no way to lose immunity; and the assumption that semi-immunes are not infectious. 

The Garki Model has had a poweful influence on malaria modeling. Several models since then have expanded on various themes. Several compartment models have been developed that replicate infection dynamics across immune stages: we call this *stage-structured immunity.* 

In the Garki Model, we can simulate the immuno-epidemiology of cohorts as they age. Eventually, the cohort *would* settle to an equilibrium. At that point, everyone is semi-immune,  a sizable fraction remains non-immune after a century. By the time the cohort reaches the steady state, everyone in the cohort has died. If we focus on the dynamics in the first two decades of life, prevalence rises as people become infected, and then it falls as people become semi-immune. The changing epidemiology as cohorts age is an important feature of malaria. In models like this, the concept of a *steady state* teaches us something, but the models draw attention to the sharp changes in malaria that occur throught the first 20 years of life. We can adapt the idea of  steady state to suit our needs -- under constant exposure, cohorts trace out *stable orbits* as they age. These stable orbits are a basis for understanding malaria dynamics *vs.* age. 

One application of these stable orbits is to understand the the relationship between age and infection prevalence as a function of exposure. Curiously, the Garki Model captures the basic shape of age-*Pf*PR curves, but it does not get the details right. When we start to look at the factors affecting the *Pf*PR by age in populations, we must acknowledge the need to add other features: drug taking and chemoprotection; differences in exposure that arise for a number of reasons; anemia, perhaps; seasonality. Not everything is about immuno-epidemiology. 

### Gametocytes and Infectiousness 

In Ross's models, everyone who is infected is also infectious. This is clearly wrong, but it may not be a terrible assumption under most circumstances. The Garki Model made the extreme assumption that semi-immune individuals are not infectious at all. There is now copious evidence that adults *do* transmit parasites to mosquitoes, but they are not as infectious. This decline in infectiousness occurs for two reasons: first, the densities of asexual-stage parasites in adults are controlled by immunity, so they are lower. Since a fraction of asexual parasites becomes gametocytes, the densities of gametocytes are also lower in adults.  Second, gametocyte densities are modulated by an immune response that affects malaria parasites in mosquitoes, which is called *gametocyte-stage transmission blocking* immunity. The dynamics of gametocyte-stage immunity change with age and exposure, and we will need to understand how this form of immunity waxes and wanes. 

There are some other important details about malaria infections that might be relevant in some contexts.  First, *P. falciparum* gametocytes take 8-12 days to mature. When combined with the 6 days in the liver, we must acknowledge that the latent period is at least 2 weeks. Because gametocytes must reach densities high enough to be transmitted, the effective latent period for humans is probably closer to 20 days. Since the parasites also need 10 days or more to mature in mosquitoes, the shortest parasite generations are probably at least a month long. 

Another feature of gametocytes that matters is that gametocyte populations are not always affected by anti-malarial drugs, so after taking drugs that clear all the asexual-stages, some people will remain infectious to mosquitoes for quite a while after being treated with some drugs. 

Ross's assumption may serve most needs, but the models must be good enough to guide policies, such as MDA or malaria elimination, when details about gametocytes and infectiousness can affect the outcomes of policies. 

### Disease 

Disease was not incorporated into most mechnanistic models of malaria until recently.  

### Treatment and Chemoprotection 

It is impossible to understand malaria infection dynamics without accounting for treatment with anti-malarial drugs and a brief period of chemo-protection that follows. The first model for drug treatment was developed to understand MDA [@DietzK1975ModelsParasitic]. In developing models for policy, we must be careful about drug taking and its effects because it modifies the relationship between exposure (the EIR) and infection. 

### The Time Course of an Infection

The time course of infections is complex, and we will need to develop some models that relate parasite densities. In the chapters that follow, we introduce two main kinds of models: 

+ AoI 

+ SoI 

### Intrahost Models 

There are two kinds of models we will discuss, but we would like to avoid them in making policy if possible.  

+ In host models; 

+ Individual-based models.  

### Synthesis

In the end, we do not need perfect models of malaria infection and immunity, but we do need a sound understanding of several things to make policy: 

+ The prevalence of infection by age as a function of exposure and drug-taking;   

    - ...in a cross-section of the population; 
    
    - ...in the care-seeking population.  

+ The incidence of malaria by severity and by age; 

+ The fraction of malaria that is promptly treated by severity and by age; 

+ The net infectiousness of a population of humans to mosquitoes. 

In the chapters that follow, we will develop some models that based on a new concept -- the age of the youngest infection -- that combine many of the ideas in the chapters above. 

## Heterogeneous Transmission

## Stratification

Human populations are heterogeneous. Some kinds of heterogeneity affect how we understand malaria and what we should do, including who to target. To deal with heterogeneity in models, we will often need to *segment* a human population into sub-populations, or *strata.* When we talk about *stratification,* we mean it the narrow sense of segmenting a human population (*i.e.* not subdividing landscapes spatially^[In a broader sense, stratification is also about subdividing landscapes into a set of spatial domains that share relevant features in order to *tailor interventions to context.* That is a topic we take up in a separate book,  (<a target="_blank" href = "/Users/smitdave/git/RAMP-Book/_book/index.html"> **Robust Analytics for Malaria Policy.** </a>).]), because the model predictions made by creating strata that are more homogeneous should be more accurate.  The guiding principle is that our analytics will should strive to be more accurate, and that we should thus identify and remove those sources of heterogeneity that would affect policy advice, whether it affects estimating the impact of interventions in the past or projecting those impacts into the future. We acknowledge that models are approximations, and that our approximations don't have to be perfect. The goal is to find ways of propagating uncertainty that are *good enough* for the task at hand. 

In malaria epidemiology, *some* kinds of endogenous heterogeneity *could* be built into the *epidemiological state space.* Other kinds of heterogeneity, including consistent differences in exposure, differences in care seeking and drug taking, and differences created by malaria control (*e.g.* net ownership or vaccination), usually require stratification. The decision about how to strike the right balance depends on the model and the purpose of a study.

The framework and supporting software offer a toolbox for stratification. It is designed to stratify populations in a principled way, so that we can *understand* how the heterogeneity affects transmission or outcomes that we care about, but we can also *combine* effects. We want to stratify populations by applying rules that *split* populations when the differences are large enough. (If we started with complex models, we might choose to *join* populations if the differences were small.) By so doing, we can *compare* the behaviors of models that differ from each other in only one way. If the differences are not too large, or if the differences in dynamical behaviors we care about are not too large, we might decide not to split the strata, and use the average.  Because of the way models are encoded, it's easy to build models that split the strata in multiple, independent ways. 




### Strata in the Ross model 

As a simple example, consider a simple Ross-style model for infection with exposure and recovery (described in Section \@ref(RossEqn)): 

$$\frac{dX}{dt} = h (H-X)-r X$$

If exposure is heterogeneous, we could split this population into two strata and add subscripts (*i.e.*, indexed by $i \in \left\{1,2, \ldots \right\}$): 

$$\frac{dX_i}{dt} =  k_i h (H_i -X_i)-r X_i$$ 

We hold the *average* FoI constant by constraining the values of $k_i$:

$$\frac{\sum_i k_i H_i}{H} = 1$$ 
Stratification is important if the differences are large. With two strata, it would not make sense to stratify if $k_1 \approx k_2$, but if $k_2 \gg k_1$ then it might change our expectations, or it might change what we recommend. 

### Frailties 

We will introduce segmentation first through models of [Heterogeneous Exposure] to malaria, where we consider various sources of *frailty* -- proportional differences in the average hazard rate for infection ($k_i$, in the example above). These differences in exposure can arise because of age, house type, risky behaviors, other factors. Frailty that is attributable to location (*e.g.* proximity of home to aquatic habitats) can be dealt with by sub-dividing space into *patches,* a topic that is taken up in [Space] below and [Spatial Dynamics]. Depending on the size of the patches, some differences in average rates of exposure due to location can persist, and these could be dealt with by generic stratification into high *vs.* low exposure strata. 

Some of the heterogeneous traits that we care about change dynamically, so we will also need to consider population *flows* among strata, which change the sizes of the strata. We would like to deal with these flows in a principled way. Bed net ownership and use are among the human behaviors that matters most for programs. In some cases, we will want to understand dynamic changes in bed net ownership, the patterns of use among those who own a net, personal protection, and community effects. Later, we show how to construct an example that *describes* all of these aspects of bednets. 

Segmentation is what we need to build models of pharmaceutical interventions with waning effectiveness, such as mass vaccination. Among the most important factors in malaria is age. We have defined algorithms to model [Aging] and other demographic change, the loss of bednets, waning protection or changing housing quality.

### Age 

Immunity to malaria develops with age and exposure. The development of immunity is probably changing throughout life, so it makes sense to think of malaria epidemiology as ontogeny. 

For systems described generically by the state space, $\mathscr X$,  the dynamics we care about have the form: 

$$\frac{\partial {\mathscr X}(a,t)}{\partial a} + \frac{\partial {\mathscr X}(a,t)}{\partial t}$$

We might want to deal with malaria differently if we are studying malaria in cohorts. In a population where the FoI over time is $h(t)$, we might want to follow a birth cohort, so we define $h_d(a) = h(t-a)$ for all $t>d$. We can then solve: 

$$\frac{d{\mathscr X}}{d a} $$
which produces states in cohorts as they age, ${\mathscr X}(a|h).$

When we simulate malaria transmission dynamics in populations for policy, we will want to put a mesh on age and segment the population. The dynamics are define for age strata, where the FoI is defined differently for each age stratum:  

$$\frac{d{\mathscr X}_a}{d t}$$

which produces age-dependent states over time, ${\mathscr X}_a(t|h).$ 

Our algorithms should guarantee that the epidemiological states over time provide an accurate match for the epidemiological states over age. 

## Humans on the Move 

The notion of a spatially distributed risk for humans and the modalities of human travel. 

+ Humans move around, so we develop a model of *time spent*. Time spent is sub-divided into three parts:

    - time spent at home; 
    
    - time spent traveling, when a night is spent away from home; 
    
    - human mobility, which describes time spent around home when not traveling.

+ For travel, we estimate a travel FoI.

+ For time at home and mobility, after weighing time spent and mosquito diurnal activity patterns by time of day, we modify time spent to get a notion of *time at risk*  

+ After modifying time at risk by search weights, mosquito blood meals are distributed among all hosts according to their availability.

### Travel 

### Mobility  

### Migration  

## Blood Feeding 

The second topic we must tackle is blood feeding, which is an interaction between mosquitoes and humans. It is an asymmetric relationship -- mosquitoes search for blood hosts, select a host, and blood feed. Humans, for their part, attract mosquitoes from a distance, move around, and spend time in places when mosquitoes are biting. Humans can wear protective clothing (or not), use bed nets (or not), or do other things that make them more or less available to humans. Despite all this, humans are often unaware that they have been bitten. 

Transmission occurs during blood feeding, and models of blood feeding *should* be able to take all this heterogeneity into account. If the models do a proper accounting, then the total number of human blood meals taken by mosquitoes would equal the number of blood meals received by humans. In doing so, we find no inspiration from Macdonald, whose description of human blood feeding was simple and phenomenological: a single parameter described the human blood feeding rates. After Garrett-Jones described the human blood index, drawing on decades of work, the one parameter was split into an overall blood feeding rate ($f$) and a human fraction ($q$). The question left unaddressed by Macdonald was how these rates vary by context, and the consequences for exposure. To do this, we reformulated the algorithm describing blood feeding [@WuSL2022SpatialDynamics].  

Over the past two decades, several papers have drawn attention to the way blood feeding behaviors are or ought to be constrained by the availability of vertebrate hosts. It may be fine to assume that the density of vertebrate hosts doesn't change, but *something* should change when a large fraction of people are using bednets. Even with static parameters, we should think through the limiting cases: if there are no vertebrate hosts, then there blood feeding should not occur (*i.e.*, $f=0$); if there are no human hosts, then there should be no human blood meals ($q=0$); and if there are no alternatives to humans, all blood meals should be on humans ($q=1$). 

The concepts we devised for blood feeding must, therefore, integrate the notion of frailty with the process of mosquito search. On the one hand, the mosquitoes should blood feed at a slower rate if hosts are unavailable. On the other hand, human biting should become heterogeneous. To arrive at an adequate description, we need to formalize this notion of host availability. 
The logic is that mosquitoes *search* for humans. Differences among humans in their attractiveness are represented by a *search weight.* Mosquito search in a place depends on the amount of time spent by humans, but also by daily mosquito activity patterns; from these, we develop a notion of *time at risk* that characterize the way human activities expose them to mosquitoes. The mosquitoes add up all the time at risk spent by all the humans, which gives a measure of their *availability.* Availability describes humans as well as other vertebrate hosts, which are modified by mosquito preferences. The overall feeding rates and the human fraction are computed from availability using *functional responses.* 

To complete the picture, we consider how the expected rate of exposure could have a distribution in the population, which we call environmental heterogeneity. 

### Search and Risk 

### Search Weights and Availability

To deal with heterogeneous exposure and many other phenomena, we need a sensible way of segmenting humans into population **strata**. Stratification makes it possible to deal with population heterogeneity. 

A new model of **blood feeding** is based on a model of blood feeding as the endpoint of a search for a blood host [@WuSL2022SpatialDynamics]. 

+ Each sub-population has a *search weight* ($w$), and the total *availability* of humans for blood feeding ($W$) is the sum of the sizes of the strata weighted by their search weights. 

+ We also consider the availability of alternative vertebrate species for blood feeding ($O$).


### Functional Response 

+ Mosquito blood feeding rates are computed using a *functional response* to total availability of vertebrate hosts ($f = F_f(B)$). 

+ To compute total availability, we add a scaling parameter on alternative hosts, because mosquito preferences can translate into different patterns of search; total availability is $B=W + O^\zeta$.  

+ The human fraction is proportional to the relative availability of hosts $q = W/B$. 

## Environmental Heterogeneity  

+ The *search weights* thus translate into a kind of **[Frailty]**, which is one component of *heterogeneous exposure.* Important sources of frailty include bednet use, housing type, and age. 

+ We also want to consider *variability* in exposure within a stratum -- what is the distribution of the *expected* number of bites over time? We have already discussed frailties, so this is a different kind of heterogeneous exposure that we call **[Environmental Heterogeneity]**.  This helps us to align models with data: mosquito counts data tend to be described well by *negative binomial* distributions, so it is likely that the distribution of infectious bites also follows a negative binomial distribution. We introduce a function that translate the EIR into the FoI: 
$$h=F_h(E)$$ 


In the Ross-Macdonald model, the underlying assumption is consistent with a Poisson distribution, but we have also derived *negative binomial hazard rates*. Environmental heterogeneity can arise from two sources: 

- the aggregated distributions of mosquitoes in micro-habitats, and the redistribution of mosquito populations by wind and weather; 
    
- random movements of humans around mosquito micro-habitats that affect their risk in a way that doesn't tend to change the mean; 

## Mosquito Behavior 

### Resource Availability

### Egg Laying 

### Search and Dispersal  

## Space

Space is big, so we start by drawing boundaries around a part of the world we want to study, that we call the *spatial domain.*  

### The Mixing Matrix 

### Pathogen Dispersal by Humans  

### Pathogen Dispersal by Mosquitoes  

To describe mosquito spatial dynamics, we 

## Time 

### The EIP 

### Seasonality 

### Exogenous Forcing  

### Vector Control  


## Mosquito Ecology  

### Regulation 

### Exogenous Forcing 

### Habitat Dynamics

## Integrated Vector Control

## Pharmaceutic Interventions 

## Context 
