# (PART) Blood Feeding, Exposure, and Transmission {-}

# Adding Realism to Models 

The kind of realism we want to include in our models is the kind that has been documented by research studies.

Malaria is complex. The Ross-Macdonald model is a good start, but we want to add the features of real systems: exogenous forcing by weather; spatial heterogeneity; multiple mosquito species with different behaviors; integrated vector control; and models of malaria epidemiology that have the features programs need. 

## Blood Feeding and Heterogeneous Exposure

Transmission occurs during blood feeding, a process that implies that requires humans and mosquitoes to be in the same place at the same time. Blood feeding is among the most difficult problems to simulate. By way of contrast, Macdonald's description of human blood feeding is simple: a single parameter describes human blood feeding rates. 
We end up describing human blood feeding in terms of a blood feeding rates (denoted $f$) and a human fraction (denoted $q$). A question for us is how these rates vary by context, and the consequences for exposure. To do this, we need to rethink the mathematics of blood feeding.  

Over the past two decades, several papers have drawn attention to the way blood feeding is constrained by the availability of vertebrate hosts. It may be fine to assume that the density of vertebrate hosts doesn't change, but *something* should change when a large fraction of people are using bednets. Even with static parameters, we should think through the limiting cases: if there are no vertebrate hosts, then there blood feeding should not occur (*i.e.*, $f=0$); if there are no human hosts, then there should be no human blood meals ($q=0$); and if there are no alternatives to humans, all blood meals should be on humans ($q=1$). On the one hand, the mosquitoes should blood feed at a slower rate. On the other hand, human biting should become heterogeneous. 

To deal with heterogeneous exposure and many other phenomena, we need a sensible way of segmenting humans into population **strata**. Stratification makes it possible to deal with population heterogeneity. 

A new model of **blood feeding** is based on a model of blood feeding as the endpoint of a search for a blood host [@WuSL2022SpatialDynamics]: 

+ Each sub-population has a *search weight* ($w$), and the total *availability* of humans for blood feeding ($W$) is the sum of the sizes of the strata weighted by their search weights. 

+ We also consider the availability of alternative vertebrate species for blood feeding ($O$).

+ To compute total availability, we add a scaling parameter on alternative hosts, because mosquito preferences can translate into different patterns of search; total availability is $B=W + O^\zeta$.  

+ Mosquito blood feeding rates are computed using a *functional response* to total availability of vertebrate hosts ($f = F_f(B)$). 

+ The human fraction is proportional to the relative availability of hosts $q = W/B$. 

If the models do a proper accounting, then the total number of human blood meals taken by mosquitoes should equal the number of blood meals received by humans. The concepts we devised for blood feeding must, therefore, translate into a model for heterogeneous exposure:  

+ The *search weights* thus translate into a kind of **[Frailty]**, which is one component of *heterogeneous exposure.* Important sources of frailty include bednet use, housing type, and age. 

+ We also want to consider *variability* in exposure within a stratum -- what is the distribution of the *expected* number of bites over time? We have already discussed frailties, so this is a different kind of heterogeneous exposure that we call **[Environmental Heterogeneity]**.  This helps us to align models with data: mosquito counts data tend to be described well by *negative binomial* distributions, so it is likely that the distribution of infectious bites also follows a negative binomial distribution. We introduce a function that translate the EIR into the FoI: 
$$h=F_h(E)$$ 
In the Ross-Macdonald model, the underlying assumption is consistent with a Poisson distribution, but we have also derived *negative binomial hazard rates*. Environmental heterogeneity can arise from two sources: 

    - the aggregated distributions of mosquitoes in micro-habitats, and the redistribution of mosquito populations by wind and weather; 
    
    - random movements of humans around mosquito micro-habitats that affect their risk in a way that doesn't tend to change the mean; 
    


## Space

Space is big, so we start by drawing boundaries around a part of the world we want to study, that we call the *spatial domain.*  

### Human Travel and Mobility

The notion of a spatially distributed risk for humans and the modalities of human travel. 

+ Humans move around, so we develop a model of *time spent*. Time spent is sub-divided into three parts:

    - time spent at home; 
    
    - time spent traveling, when a night is spent away from home; 
    
    - human mobility, which describes time spent around home when not traveling.

+ For travel, we estimate a travel FoI.

+ For time at home and mobility, after weighing time spent and mosquito diurnal activity patterns by time of day, we modify time spent to get a notion of *time at risk*  

+ After modifying time at risk by search weights, mosquito blood meals are distributed among all hosts according to their availability. 

### Mosquito Dispersal

To describe mosquito spatial dynamics, we 

## Time 

## Epidemiology 

## Mosquito Ecology  

## Control

## Context 
