# (PART) Introduction {-}

# The Prevention of Malaria 

Ronald Ross is best known for being the first person to observe malaria parasites in a mosquito [@RossR1897PeculiarPigmented]. The event -- on August 20$^{th}$, 1897 in a military hospital in Hyderabad, India -- is now celebrated as _mosquito day_.
In the months that followed, Ross made the case that mosquitoes transmit malaria parasites [@RossR1898RoleMosquito]. 
Concurrently, the life-cycle of human malaria parasites was described by an Italian team, led by Giovanni Battista Grassi [@GrassiB1898UlterioriRicerche;@GrassiB1901StudiDi]. 
By 1899, a scientific consensus had formed among malaria experts that malaria was a mosquito-transmitted disease. 
It would take some time before the "mosquito hypothesis" was accepted more broadly.

The discoveries made by Ross and Battista Grassi closed a loop that Charles Laveran had opened in 1880 when he identified malaria parasites in blood, providing the first clear evidence that human malaria was a parasitic disease [@Laveran1880;@Laveran1884].
Laveran's observation had spawned almost two decades of research describing malaria infections and disease in humans, all before the mode of transmission was known [@GarnhamPCC1988HistoryDiscoveries]. 
The modern view of the parasite life-cycle was not complete until the 1940s, through research describing the parasite's liver stages by Garnham and colleagues [@ShorttHE1948PreerythrocyticStage;@GarnhamPCC1988HistoryDiscoveries]. 


Malaria is a disease that could be treated and measured before anyone knew what caused it or how it was transmitted.
Malaria was commonly treated with quinine once the compound had been isolated in 1824. 
The chemical compound was isolated from the bark of Cinchona tree, which had been used to treat malaria fevers.
The spleen rate, a reasonable metric for malaria was described by Dempster in 1948 [@Dempster1848SpleenRate].
All of this occurred before Laveran showed how that malaria was caused by infection with a parasite.

The elements of the story of malaria, including a full account of
how the malaria parasite's life cycle was unravelled over time is a topic that worth taking some time to learn [@Bruce-ChwattLJ1988HistoryMalaria;@GarnhamPCC1988HistoryDiscoveries;@ServiceMW1978ShortHistory;@CoxFEG2010HistoryDiscovery]. 


Knowing the mode of transmission, the British military launched vector control efforts to protect British citizens from malaria in its colonial empire.
At the time, vector control with bed nets and larval source management, and malaria was treated with quinine.
Lest we imagine malaria control in this era was for general humanitarian purposes, Ross emphasizes population segregation as a useful mode of malaria control for the colonizers. 
Both Ross and Laveran were military doctors supporting colonial governments, a fact that we acknowledge that we can neither ignore nor excuse.
We try to learn enough history to avoid repeating the same mistakes.
We are sure to make enough mistakes of our own as we blunder forward.

In this first epoch of malaria control, it is Ross who once again draws our attention.
After his big discovery, Ross turned his attention to malaria control. In 1910,
he published a book, *The Prevention of Malaria.* A second second edition followed in 1911.
Ross's work on malaria prevention is of interest because he laid out a vision for a quantitative approach to the prevention of malaria.
He clearly articulated how malaria control needed quantitative concepts, including well-developed metrics to measure malaria in populations. 
Ross himself developed the thick film, a technique that was intended to increase the sensitivity of malaria diagnostics [@RossR1903ThickFilm; @RossR1903ImprovedMethod].
In the service of understanding malaria for purposes of control, Ross developed the first mathematical models for malaria, in which he addressed basic questions about larval source management [@RossR1905LogicalBasis] and malaria transmission [@RossR1908; @RossR1911Book; @RossR1911Nature].

In the second decade of malaria control, the last phase of Ross's career, he formed an alliance with Hilda Hudson, a mathematics professor from Cambridge University. Between 1915 and 1917, Ross and Hudson developed mathematical theory to support the study of epidemics, which they called *a priori pathometry.* Then, in 1921, Martini developed a model describing the dynamics of infections that immunized their hosts. In 1927, Kermack and McKendrick published the first of a five-part series on the mathematical theory of epidemics that described the dynamics of acute immunizing infections, which overshadowed the work by Ross and Hudson. Nowadays, the field is called *mathematical epidemiology.*   

*** 

The parasite's life-cycle has been an organizing principle for the study of malaria. 
The discoveries by Laveran, Ross, Battista Grassi, Garnham and others set the stage for hundreds of thousands of studies over 144 years (at the time of this writing) that have developed a rich and impressive body of knowledge. 
Over that time, we have learned an enormous amount about malaria and its control. 
The first comprehensive review of malaria, *Malariology. A Comprehensive Survey of all Aspects of this Group of Diseases from a Global Standpoint,* was published in 1949 in a two volume set edited by Mark F. Boyd with 
70 chapters and 1643 pages from 65 contributors [@BoydMF1949MalariologyComprehensive]. 
Almost 40 year later, 1988, the second comprehensive review of malaria was published in another two volume set, *Malaria: Principles and Practice of Malariology,* 
edited by Walter H Wernsdorfer and Sir Ian McGregor; this set had 57 chapters and 1818 pages from 68 contributors, [@WernsdorferWH1988MalariaPrinciples]. 
Another 40 years has passed, and it is almost time for an update. 


This book is a primer on mathematical models to support robust analytics for malaria policy (RAMP). 
It covers malaria epidemiology, mosquito ecology, human demography, and malaria transmission dynamics and control with a focus on the mathematical theory and models that have been developed over the past century. 
While this book will cover many of the topics in those two-volume sets, it is focused more narrowly on introducing the mathematical study of malaria that started with Ross.
The field made some great leaps forward in the 1950s, when Macdonald wrote a series of papers that reviewed decades of field studies and updated Ross's basic models. 
Macdonald's paper on the sporozoite transformed the quantitative study of malaria transmission by mosquitoes, drawing attention to the importance of mosquito survival.
In his next paper, Macdonald presented a formula for the basic reproductive number for malaria, an idea that almost certainly traces back to Alfred Lotka's work in human demography.
Macdonald would have known Lotka from his extensive work on Ross's models of malaria. 
The simple mathematical models, now called *the Ross-Macdonald model*, thus defined basic theory for malaria transmission dynamics and control [@SmithDL2012_RossMacdonald].
This book starts with the Ross-Macdonald model, and it covers a rich and wonderful set of models that has grown out of it. 
Around 1970, the mathematical study of malaria entered a period of elaboration through the work of Klaus Dietz, Norman TJ Bailey, Joan Aron, Barbara Hellriegel, and others. 
Ross was a pioneer in a field that has included important contributions by hundreds of scientists and analysts. 

Nowadays, we can describe malaria as a managed, complex adaptive system involving non-linear interactions among mosquitoes, parasites, humans, and the managers. Malaria systems are heterogeneous and locally peculiar in some way: doing the same thing in different places can result in different outcomes. To understand why outcomes of malaria control vary, we need good theory for malaria, including malaria transmission intensity and seasonality, mosquito ecology and behaviors, mosquito and parasite genetics, health systems, and human behaviors. To give advice, we need malaria intelligence -- information about these critical factors, and since the systems are peculiar, we will need local information to give tailored advice. We must grapple with questions about malaria that remain poorly understood, and we most offer advice even if there are enormous gaps in data and knowledge. We want to give policy advice that is robust to uncertainty. We will need well organized systems to store and analyze data and to develop intelligence that can help us learn and adapt. In all of these activities, mathematical models of malaria transmission dynamics and control play an important role. 
In this book, *Applied Malaria Dynamics: Theory and Computation for Robust Analytics and Adaptive Malaria Control*, we take a deep dive into dynamical systems models for malaria epidemiology, transmission dynamics, and control. It is designed to serve as an introduction and resource for malaria analysts who seek to use evidence and mathematical models to develop advice about malaria policies. We introduce the material using a modular framework for building malaria models designed to suppport RAMP [@WuSL2023SpatialDynamics]. Most of the examples use one of two RAMP-branded R packages: one is designed to build and solve systems of ordinary or delay differential equations [ramp.xde](https://dd-harp.github.io/ramp.xde/); and the other supports discrete-time systems [ramp.dts](https://dd-harp.github.io/ramp.dts/). These are further supported by other ramp software packages, including model libraries, and other simulation software that takes a deep dive into mosquito ecology, mosquito dispersal, malaria epidmiology (in the narrow sense).  We also hope that the material can be used in scientific research. 

To get all this started, we will walk through concepts as they developed over time, which brings us back to Ronald Ross, the study of the prevention of malaria, and the study of epidemics.^[The narrative in this book is often historical, which serves two purposes.
First, it provides an excuse to cite and discuss old papers that should not get overlooked.
Second, a historical narrative allows us to introduce malaria complexity in an ordered way, starting from principles that are simple and abstract, and progressing towards ideas that are non-linear, messy, or subtle.
We will often use history as a way of structuring discussions, even as our attention turns increasingly to the mathematics we need to deal with the biological complexity of malaria in populations.]

## The Quantitative Approach

The goal of malaria control is to prevent malaria. In the long-term, the expectation is that malaria will be eliminated from an ever growing list of places, and that it will eventually be eradicated. 
All of this revolves around the study of malaria transmission by mosquito populations through blood feeding.

Since malaria is a mosquito-transmitted diseases, malaria control programs need some basic theory to understand how malaria (*i.e.* any disease that is caused by infection with the parasite) is related to exposure risk, malaria transmission intensity, and the prevalence of infection. 
In particular, programs should should have a basic understanding that relates the factors driving malaria in a place, the metrics that we use to measure malaria, mosquito population densities and bionomics, and the actions taken by malaria control programs. 

A vision for doing all this was articulated by Ross in the first decade of studying malaria transmission.
Ross was not the only one to grapple with the complex, multi-factorial nature of malaria transmission and vector control, but what set him apart was his attempt to use of mathematics to illustrate his ideas about malaria. 
We will use Ross's writings throughout this chapter to introduce the nature of the challenges of managing malaria control. 
With the benefit of decades of research and cheap high-speed computing, we are in a better position to fulfill that vision than Ross ever could have.  

At the end of this chapter, we make some attempt to put Ross into a broader historical narrative.

*** 

In 1899, Ross announced a new phase of his career in a pair of essays on *exterminating* or *extirpating* malaria through mosquito control  [@RossR1899ExterminationMalaria;@RossR1899InauguralLecture]. Ross's initial focus was on larval source management: 

> *...in order to eliminate malaria wholly or partly from a given locality, it is necessary only to exterminate the various species of insect which carry the infection. This will certainly remove the malaria to a large extent and will almost certainly remove it altogether. It remains only to consider whether such a measure is practical [@RossR1899ExterminationMalaria].*

Over the decade, Ross began to use quantitative concepts to understand some very basic questions. Ross was interested in using mathematics to help him reason through problems. 
Among Ross's early writings, we find a question posed in 1902, in *Mosquito Brigades and How to Organise Them* [@RossR1902MosquitoBrigades]: 

> It may now be asked, what percentage of diminution in mosquito-borne diseases may be expected to follow a given percentage of reduction in the number of mosquitoes? I regret that I cannot as yet give any actual statistics on the point, but we may perhaps attempt an estimate on *a priori* grounds. We ask, are we to expect a decrease in the same ratio as the decrease in the number of mosquitoes; or in a dupblicate ratio? The disease will probably diminish in a duplicate ratio? ---pp. 56 in [@RossR1902MosquitoBrigades]

Ross was thus trying to develop quantitative intuition to establish reasonable expectations about malaria transmission and the responses to mosquito control. His guess was that the responses should be non-linear because two bites are required for transmission -- one to infect a mosquito and another to transmit it back to humans. In paragraph that follows, Ross explains what he meant by a *duplicate ratio.* 

> Now, if we reduce the number of mosquitoes in the locality by one-half, the mosquito bites also will be reduced by one half; and, consequently, only half as many people will now become infected as was formerly the case. But, since the mosquitoes themselves are infected by biting previously infected persons, the percentage of infected mosquitoes ... will also be reduced in its turn, because the insects will now find fewer infected persons to bite. Hence, ultimately, the number of infected persons in the locality will be reduced by much more than one-half. In fact, we may perhaps assume that the number of infected persons will be reduced to one-quarter, that is, in the duplicate ratio of the percentage of reduction of the mosquitoes. ---pp. 56 in [@RossR1902MosquitoBrigades]

While Ross was right that there should be a non-linearity, his quantitative logic failed when he tried to use it without going the rigorous process of developing and analyzing a mathematical model. 
Using mathematical models, we would now argue that, in fact, the expected reduction varies from place to place.
The response would depend on the intensity of transmission before doing any control, which scales linearly with the density of mosquitoes.
When transmission is very intense, halving mosquitoes would scarcely change the fraction of humans infected.
In some places, halving mosquitoes might be enough to end local malaria transmission. If malaria transmission were sustained through malaria importation, then Ross's answer would not be too far off. 

Despite getting the logic wrong -- or at the very least, underestimating the complexity of the question -- Ross was asking relevant questions. 
In this case, we was asking about *scaling relationships* in malaria transmission and their causes.
The search for an *a priori* approach would eventually lead to development of his first mathematical model for malaria transmission in 1908, in *Report on the Prevention of Malaria in Mauritius* [@RossR1908]. A clear basis for giving an answer would finally come when Lotka analyzed Ross's models in 1923 [@LotkaAJ1923part1; @LotkaAJ1923part2; @LotkaAJ1923part3; @LotkaAJ1923part5], and in Macdonald's analysis of the sporozoite rate [@MacdonaldG1952Sporozoite] and his formula for the basic reproductive number for malaria [@MacdonaldG1952R0]. The study of these scaling relationships is still evolving.  

Ross also discused response timelines. He was aware of differences in duration of infection for yellow fever, lypmhatic filariasis, and malaria. Compared to yellow fever, the responses to vector control should be slow because,  

> ...the parasites remain alive for years after the first moment of introduction by the mosquito.... We must not, therefore, expect to see malaria vanish, as if by magic, immediately after our campaign against mosquitoes. -- pp. 53 of [@RossR1902MosquitoBrigades]

In all this, Ross was asking thus questions about what would determine the outcomes of malaria control. 

What other factors could affect what was observed? One of the arguments against the "mosquito hypothesis" had been that malaria was sometimes found in places where there was no evidence for malaria transmission. In *The Prevention of Malaria,* Ross spends a great deal of time discussing the importance of imported malaria. In the chapters that follow, we will follow this idea through to its logical conclusion. 

## Larval Source Management 

The interest in mosquito populations originated from an academic discussion, in 1904, that critiqued a larval source management program in Mian Mar. One fact that clearly irked Ross was the lack of any good method for measuring mosquito populations accurately. The problem at hand: 

> Suppose that we have to deal with a country of indefinite extent, every point of which is equally favorable to the propagation of gnats (or of any other animal); and suppose that every point of it is equally attractive to them as regards food supply; and that there is nothing, such for instance as steady winds or local enemies, which tends to drive them into certain parts of the country.- Then the density of the gnat population will be uniform all over the country. Of course, such a state of things does not actually exist in nature; but we shall nevertheless find it useful to' consider it as if it does exist, and shall afterwards easily determine the variations from this ideal condition due to definite causes. Let us next select a circumscribed area within this country, and suppose that operations against the insects are undertaken inside it, but not outside it. The question before us is the following: How far will these operations affect the mosquito density within the area and immediately around it?

Ross's question was:

> How large must that radius be in order to render the center entirely mosquito-free?


## Malaria Population Dynamics

He recognized that prevalence could change, and that what set its value was a balance between two processes. The quantitative logic looks like this: 

$$
\left[
\begin{array}{rcl}
\mbox{Fraction Infected Today} &=& \mbox{Fraction Infected Yesterday} \;\; -\\
&& \mbox{Cleared Infections} \;\; + \\
&& \mbox{Fraction Uninfected that Got Infected}\\
\end{array} \right]
$$

This description ignores malaria importation, infected people who died, infected people who emigrated, and infected people who immigrated. The model is neither comprehensive nor perfect. It was a starting point. 

For short-lived mosquitoes, we assume they are much more likely to die than to clear infections. So for mosquitoes, the process is slightly different: 

$$
\left[
\begin{array}{rcl}
\mbox{Fraction Infected Today} &=& \mbox{Fraction Infected that Survived} \;\; -\\
&& \mbox{Fraction Uninfected that Got Infected}\\
\end{array} \right]
$$

What's important here is that infectious mosquitoes are infecting people when they bite, and infectious people are infecting mosquitoes when the mosquito blood feeds.

In planning and evaluating malaria control, it was important to develop some kind of expectations about where and when to do malaria control, what types of malaria control are likely to work best, and so on.  

Despite all the focus on malaria, transmission Ross's first mathematical model of malaria was about mosquito populations. 

In 1911, Ross formulated a model (his second) as a system of two ordinary differential equations. The model appeared in the $2^{nd}$ edition of _The Prevention of Malaria_ [@RossR1911Book], and it also appeared in _Nature_ [@RossR1911Nature] in this form: 

$$ 
\begin{array}{rl}
dz/dt &= k' z' (p-z) + q z \\
dz'/dt &= k z (p'-z') + q' z' \\
\end{array}
$$ 

## Measuring Transmission 


Through the first half of the 1900s, Ross promoted malaria control and malaria research.
He was a key player in public debates about malaria control and he launched a center to study malaria transmission that is still active today [@BockarieMJ1999ItAll;@SmithDL2012_RossMacdonald].
He engaged in public debates about malaria control hosted by the _British Medical Journal_, and he published a book, _Mosquito Brigades and How to Organize Them_ [@RossR1902MosquitoBrigades].
The end of this phase of his career was marked by publication of the  $2^{nd}$ edition of _The Prevention of Malaria_ in 1911 [@RossR1911Book].


This phase of Ross's career is highly relevant to our study of **Applied Malaria Dynamics** because it was the beginning of a rigorous approach to malaria control including development of the first three mathematical models describing malaria transmission dynamics or control [@RossR1905LogicalBasis;@RossR1908;@RossR1911Book;@RossR1911Nature].
Many of the early attempts to control malaria were implemented by the British Military. In the first few years, there were some successes, but there were also some failures [@RossR1907PreventionMalaria]. 
Heterogeneity in the responses to malaria control efforts seem to have turned Ross to mathematics. 
In 1904, he presented a paper at the International Congress of Arts and Science in St. Louis, Missouri that applied diffusion models to larval source management (published also in _Science_[@RossR1905LogicalBasis]). 
Ross's transmission models appear in publications that emerged from consulting with national malaria programs in Mauritius and Greece [@RossR1908;@RossR1909]. 
While he was writing about the nuts and bolts of control, he was also grappling with mathematical formulas that could help him understand malaria control quantitatively. 
How would reducing mosquito densities change the prevalence of malaria? 
Was there a critical population density of mosquitoes required to sustain transmission? 
The result was the first mathematical model to describe malaria transmission dynamics [@RossR1908]. 
A short time later, Ross would reformulate the model in the $2^{nd}$ edition of his book, _The Prevention of Malaria_ [@RossR1911Book]. 
He also published it in Nature [@RossR1911Nature]. For Ross, the mathematical models were a logical next step towards trying to understand malaria control in rigorous quantitative terms.

## The Study of Epidemics 

By 1915, when Ross turned his attention to the broader study of epidemics, his intent was to establish a new discipline, which he called _a priori pathometry_.
He set out to establish the mathematical foundations for the study of epidemics [@RossR1915AprioriPathometry;@RossR1916ApplicationTheory].
In his 1916 paper, he wrote  

> *It is somewhat surprising that so little mathematical work should have been done on the subject of epidemics, and, indeed, on the distribution of diseases in general.* 

The case for using mathematics had grown stronger as a result of a scientific revolution caused by invention of the light microscope that established a germ theory of disease, which included Laveran's discovery in 1880. Even without knowing that bacteria, viruses, and parasites were transmitted among hosts causing disease, *contagion* was an impossible concept to ignore. Some mathematical work had already been done on infectious diseases, including a few models. It's not clear whether Ross was aware of Daniel Bernouli's mathematical model of small pox [@BernoulliD2004AttemptNew;@BacaerN2011DanielBernoulli], or PD En'ko's discrete time models for measles [@DietzK1988FirstEpidemic]. 
Ross may have known about those models, but he certainly didn't cite them. 
Regardless, the mathematical study of infectious diseases in populations was, at that point in time, underdeveloped. 
Ross wrote:

> *...the principles of epidemiology on which preventive measures largely depend, such as the rate of infection, the frequency of outbreaks, and the loss of immunity, can scarceley ever be resolved by any other methods than those of analysis.*

Ross proposes a rudimentary three-tiered classification system for epidemics based on the patterns of fluctuating incidence with exemplars: 1) leprosy and tuberculosis; 2) measles and malaria; 3) plague and cholera. 

> *To what are these differences due? Why indeed should epidemics occur at all, and why should not all infectious diseases belong to the first group and not always remain at an almost flat rate?*

In 1917, he teamed up with Hilda Hudson, a Cambridge mathematician, to finish the first major contribution to mathematical epidemiology, or what he called _a priori pathometry_ [@RossR1917AprioriPathometry2;@RossR1917AprioriPathometry3].
Over 18 years (1899-1917), Ross's ideas laid a solid foundations for the modern study of malaria transmission and theory of malaria control [@SmithDL2012_RossMacdonald].

## Mathematical Epidemiology

Despite the heroic efforts of Ross and Hudson on _a priori pathometry_, they were missing a key element in the modern mathematical study of epidemics. In 1920, a new mathematical model was published by Martini, which described epidemics in which recovery from infection was followed by lifelong immunity. 
Martini's model would be explored in great detail in a series of papers by Kermack, and Mckendrick. 
In modern language, Ross's models would be studied as SIS compartmental models, while Martini's equations would be called SIR compartmental models.
The two systems of equations have strikingly different features, and so do the kinds of epidemics they mimic. 

In Ross's model, a person would become susceptible to infection after recovering, so a person could be infected many times, and prevalence is a naturally meaningful statistic. In fact, Ross's equations can be solved exactly: after Ross published the equations in Nature in 1911 [@RossR1911Nature], Alfred Lotka published a closed-form solution in 1912 [@LotkaAJ1912Nature]. 

There is no closed form solution to the SIR model, and prevalence is an ephemerally changing quantity.
The natural summary statistic for SIR epidemic is called $S_\infty$, the portion remaining uninfected asymptotically. 
In simple epidemics -- an epidemic in a single population with no replenishment of susceptible hosts -- the dynamics differ depending on how many cases that first case would tend to generate, called $R_0$. 
If $R_0 < 1$, then there is a closed form solution: $S_\infty = S_0 - I_0(1-R_0)^{-1}$. 
If that first case would generate more than one other case, and the number of cases would initially rise to a peak, when each new case would generate exactly one case. 
Thereafter, the number of cases would decline. 
The time course of an SIR epidemic does not have a closed form solution. 

The differences between SIS and SIR models would provide a mathematical basis for answering Ross's question and point to an important role for the concept of population immunity.
In SIS models, there is no immunity, so prevalence tends to approach an endemic equilibrium with very little tendency to cycle.
When susceptible populations the SIR models are replenished by birth or migration, there is a natural tendency to cycle.

The SIS model is a useful starting point, but Ross was aware of evidence that immunity to malaria would develop in humans. 
The role of immunity is more complex, but a critical feature is that infection with one parasite would not prevent reinfection with another.
In places where exposure rates were high, reinfection -- also called *superinfection* -- was quite common. 
The first model of malaria that was *not* an SIS model -- published by George Macdonald but relying on mathematics by P. Armitage -- 
considered a role for *superinfection,* or reinfection of susceptible individuals. 
In models with superinfection, an interesting statistic is the multiplicity of infection (MoI).
A useful discussion of this superinfection model and its mathematical flaws was written by Paul EM Fine [@FinePEM1975SuperinfectionProblem].
What is, perhaps, more important is that superinfection in malaria facilitates sexual recombination for the parasites.
Sexual recombination facilitates development of parasite diversity, which could partly explain population immunity in malaria.  

Sticking with Ross's core challenge of how to study epidemics mathematically to understand the tendency to cycle, we must acknowledge 
the complex natural history of population immunity. In malaria,
a model for the mathematical talents of Klaus Dietz combined with the epidemiological skills of Louis Molineaux to produce the first model of population immunity to malaria. 
That model described infection dynamics in a population with partial immunity.
In malaria epidemiology, a core challenge is the problem of malaria immunity and its relationship to parasite genetic diversity, disease, and infectiousness. 
In the mathematical study of malaria epidemiology, the formulation of adequate models is among the most pressing and most difficult to address. 
Measles and a few other pathogens are well-described by the SIR model. 
For these  acute immunizing infections, infection is followed by a life-long immunity.
The dengue viruses has four (or maybe five) functionally distinct virues with complex patterns of cross immunity. 
For other pathogens, population immunity is undermined when immune-escape variantes evolve in the pathogen populations. 
For the influenza viruses and the coronavirus descendents of the viruses that sparked the global COVID-19 epidemic, escape variants arise at a rate that is high enough to sustain yearly outbreaks.  

Adding to the complexity, immunity is not the only factor affecting a tendency to cycle. 
For arthropod-transmitted pathogens, fluctuations in arthropod population densities and behaviors driven by weather affect trasmission rates. 
For directly transmitted pathogens, humidity and survival in the environment and the tendency for populations to congregate amplifies transmission. 
In malaria, fluctuating mosquito one factor that must *a priori* force transmission, and since population immunity probably has a weak effect, 
seasonal malaria is largely driven by fluctuating mosquito populations. 
In SIR models, seasonal fluctuations are sustained by an interaction between environmental factors and the depletion of susceptible individuals. 


## Approaching Complexity 

Malaria is complex and heterogeneous, which makes it difficult to study and manage. A core challenge in both science and policy is the availability of information. Mathematical models can help us understand and analyze all that complexity and make informed decisions, despite the data gaps. 

While this book is about applied dynamics, the approach is eclectic. It relies heavily on conventional statistical analysis. An axiom we espouse is that two inferential approaches are better than one. This point of view was prominent in the early study of epidemics, tracing back to both Ross and Browne [@FinePEM1975RossPriori]. After Ross spent a decade studying malaria control, he realized the difficulty of understanding malaria epidemics, so he argued for an integrated approach. About the study of epidemics, he wrote 

> *The whole subject is capable of study by two distinct methods which are used in other branches of science, which are complementary of each other, and which should converge towards the same results -- the **a posteriori** and the **a priori** methods. In the former we commence with observed statistics, endeavor to fit analytical laws to them, and so work backwards to the underlying cause (as done in much statistical work of the day); and in the latter, we assume a knowledge of the causes, construct our differential equations on that supposition, follow up the logical consequences, and finally test the calculated results by comparing them with the observed statistics.* 

More than a century later, it is much easier to use computational tools to fulfill this vision. 

While this lays out a useful agenda for *understanding malaria,* another axiom we espouse is that the process of giving advice about a policy must take on a broader set of challenges. 
Policy and science are different in many ways, so there are good reasons why we might want to use different models and methods for basic research and policy analytics. 
In policy, decisions *must* be made in a timely way, and they *should* use all available evidence, even if it's weak. 
Basic research is epistemologically conservative, by design. 
Studies that are published in peer review must be repeatable, and in anticipation of criticism, the scientists aim to do things so well that they are unassailable. 
This usually has the effect of narrowing and controlling the conditions under which the study was conducted.
When we operate in policy settings, we *should* design our studies in a different way, and we will thus need to deal with the uncertainty differently. 
The studies that inform policies will need to take an approach that is broader -- the models should be realistic enough to address the question of interest. 
Such studies will often need to make compromises and decisions that are poorly informed by the evidence, which raises the question of how much a policy maker could trust it.
One strategy for making policies trustworthy is to repeat the supporting analysis using every reasonable approach, so that we can be reasonably sure our policy recommendations would not change. 
The idea of fully propagating uncertainty is the essential feature of *robust analytics.*
If we make the effort, we can identify key sources of uncertainty, identify priority data needs, and collect new data that could help resolve some of the most important sources of uncertainty. 
Building models to do this is challenging for practical reasons, and it requires drawing heavily on basic research.
In giving advice, we must give different weights to the uncertainty than we would in research. 

In basic research, we develop mechanistic models to understand malaria as a biological process. In malaria epidemiology, the states and parameters describe infection, immunity, infectiousness, disease, and drug taking in response to exposure. Scientists focus on basic biological mechanisms in order to understand differences in malaria across spectrum of transmission. Immunity and drug-taking are important factors to consider, but it may be that differences in epidemiology and disease across settings arise from differences in the local parasite populations. The models are a way of summarizing knowledge in a quantitative form -- something like a complex hypothesis. A test of a model's adequacy is whether it can describe malaria accurately after accounting for differences in drug taking patterns and pattern of exposure. 

We study mosquito ecology and blood feeding to understand malaria transmission and develop theory for malaria control. Transmission models couple parasite infection dynamics in humans and mosquitoes through blood feeding. Mosquito populations are shaped by the aquatic habitats for immature mosquito populations. These habitats are standing water bodies, and they are shaped by topography, hydrology, land use, and the water chemistry, which is affected by surrounding rocks, soils, vegetation and pollution. These habitats are filled (exogenously forced) by rainfall and after some eggs are laid, the mosquito dynamics are affected by crowding, predation, and other endogenous dynamics. Larval development and parasite development rates are modified by temperature. Adult mosquito activity rates are affected by temperature, relative humidity, and vector control. Indoor residual spraying (IRS) kills mosquitoes when they rest on a sprayed surface, usually after blood feeding or during the process of searching for a host. Insecticide treated nets (ITNs) protect humans from biting and kill some mosquitoes. By reducing the availability of potential blood hosts, nets can slow blood feeding in some contexts. Larval source management (LSM) reduces immature population densities. 

By studying mosquito ecology and malaria transmission dynamics, we can start to understand malaria as a changing baseline that has been modified by malaria control. This is the problem confronted daily in malaria programs, but dealing with the evidence requires having the tools available to synthesize data describing different parts of malaria. The models help translate evidence into information that can be used to make decisions, to make strategic plans, and to mark progress against national plans. The models encapsulate information about transmission in context, so it is possible to study how malaria persists in a place over time, and how various factors have modified (or could modify) mosquito population dynamics and blood feeding and thereby suppress transmission. Transmission models help us to set intervention coverage targets based on an understanding of malaria connectivity to surrounding regions and local thresholds. 

In policy, we use these models with the expectation that -- if we fit the models by adjusting parameters that affect how malaria works in some particular place -- they *should* help us understand transmission in some particular context and make good decisions about what to do. 

Frustratingly, the heterogeneity and the complexity conspire against us. We would like to be sure about how malaria works across settings before we start using the models to stratify populations, tailor interventions to context, or targeting the interventions. Instead, we must admit that we don't know everything we'd like to, and we probably never will. We must proceed with policy without having satisfactory answers to some basic questions. In policy, we will use the models to evaluate the consequences of having missing information, but we will also use the models to help us prioritize missing data so we can fill in the gaps. What missing data would reduce our uncertainty about what to do about malaria? How do we fill the critical knowledge gaps. 

To understand malaria or to give policy advice, we must start simple and then add complexity, layer on layer. To deal with missing information, we start with generic models, and then add details to address concerns about some of the details that we hope to identify by studying the systems as we intervene. This approach -- starting simple and then layering on complexity -- makes it possible to learn as we go. A question is when it stops making sense to add realism to a model. A model that it too simple and abstract might help us understand the basic dynamics and give generic advice, but we would question the model's adequacy if it could not reproduce the patterns we cared about in some particular place at some particular time. As a rule of thumb, a model should be just complex enough to *describe* the patterns we care about and *weigh* the relevant options to give advice. Practically speaking, it's hard to know you've gone far enough unless, at some point, it's clear that you've gone a bit too far.

Over the past few years, we developed a new framework for building models that would make it possible to start simple and then build models of malaria transmission at any level of complexity. We wanted to be able to build in realism by adding complexity one feature at a time. Through this process we can create nested, hierarchical models in branching chains. At the ends of the chains, we might find highly realistic models that are, perhaps, overfit. (The cautions against overfitting play out differently in policy given the urgency of acting in a timely way, but it is also possible to go out and collect new data.)  We call the framework's ability to do this **scalability** and the resulting swarms have **scalable complexity.** The iterative attempt to make plans, weigh evidence, quantify uncertainty, gather new data to reduce uncertainty, and then restart the annual cycle, is called **adaptive malaria control.** 

To make this possible, we needed a way of building models that would keep the focus on the policy questions and on a dialogue between malaria managers and the analytical support team. We thus sought to design modular software with *plug-and-play* functionality and a high degree of structural flexibility. We needed the framework to be extensible. After making a lot of mistakes, the primary design phase is over, and the algorithms have been published in two software packages. We are currently extending the library of *base models*, which includes some simple or classical models that are instructive or of historical interest. We are also fine-tuning the design requirements for models as we develop protocols that streamline fitting models to data. The software avoids the mistakes we made over the past few years, reuses models, and streamlines the model building process. We hope this software has dramatically lowered the costs of building and analyzing these complex, realistic models. 



In malaria epidemiology (narrowly defined as a study of infection and disease in humans), the relationship between exposure, infection, immunity, disease, and infectiousness changes in populations as they age, and it is affected by drug taking. This picture grows more complex as we consider intervening with vaccines or monoclonal antibodies, or as we look at interactions with anemia, nutritional status, and human genetics. Our models need to interface with data from clinical settings and research, so they will need to consider diagnostics, parasite counts, detection, and transmission. Combining these factors can give rise to an overwhelming amount of complexity. Later, we will introduce new models and show how it possible to simplify all this complexity and make sense of malaria.  

We are interested in using these models to guide policy, which requires both solid computation and good communication. In this book, we lay a foundation for understanding the complexity by studying some simple compartmental models. We will review classical queuing models for superinfection and the multiplicity of infection (MoI); new models for the age of infection (AoI) or stage of infection (SoI); immunity; parasite densities, fever, disease, and detection; gametocytes and transmission, and drug taking. To end up with models that can handle all the complexity, we build probabilistic models that combine these factors. In doing so, we find that we can do some powerful analysis, and we can map the states in these models onto outcomes that matter for research and policy: test positivity, parasite counts, infectiousness, and disease. With patience, we can combine these factors and develop a framework for understanding malaria in populations that match the features of individual-based simulation models. We end up with a sensible understanding malaria epidemiology as ontogeny -- development of immunity as a part of an organisms history. We back this view with some very usable models that capture the changing character of malaria in cohorts of humans as they age. 

We are interested in understanding malaria control in context, which requires delving into mosquito ecology and behavior. In this book, we start with a simple model for mosquito ecology and parasite infection dynamics in mosquitoes. We add aquatic population dynamics, mosquito population regulation, and exogenous forcing by weather. Later, we worry about adult mosquito behavioral states such as mating, sugar feeding, and egg laying. We introduce the concept of resource availability, and we develop an understanding of mosquito search and movement in response to resource availability. We take some deep dives to understand how mosquito spatial dynamics work at a fine spatial grain, and then we scale up to understand mosquito populations on landscapes. 

At first, we describe mosquito blood feeding and transmission with a few simple parameters. Later, we develop a new model for mosquito blood feeding in a dynamically changing host population with parameters that allow host strata to be more or less available. We also modify our understanding of heterogeneous exposure to biting. We develop a methods for modeling environmental heterogeneity, heterogeneous exposure by age, and a generalized way of handling [failty](Frailty)--  other sources of heterogeneous biting -- through stratification. 

We must take a detour to understand how to handle the effects of temperature on the parasite's extrinsic incubation period (EIP). We need a way of dealing with mosquito survival and dispersal through the EIP. This problem has been effectively solved.  

To round out this picture, we need a way of dealing with other aspects of human ecology that affect malaria transmission dynamics, including human mobility, human demography, bed net usage, adherance to drugs, and care seeking. Differences among humans call for a synthesis of studies that have identified traits that affect malaria, stratification, and simulation to identify useful ways of propagating the heterogeneity through analyses.  

To go along with a theory of transmission, we need a theory of control. We compute effect sizes and evaluate area effects. We develop a generalized concept of effect modification that considers the total effect of a single unit of control. We modify basic processes by including the effects of vector control and mass medical interventions (*e.g.* seasonal malaria chemoprotection, mass drug administration, vaccines, and monoclonal antibodies). Relying on behavioral state models and the concept of resource availability, we develop a models for integrated vector control. 

This is a book about how to do the math that is required for robust analytics for malaria programs. The goal is to use all the data available, but especially the data generated by malaria programs, to paint a clear picture of malaria transmission as a changing baseline that has been modified by control. 

## Historical Notes 

### The Light Microscope



### Mathematical Epidemiology Before Ross 

We note that contemporary scholars of Ross, including Brownlee and Lotka, were also applying mathematics in human demography and health.
Ross's mathematical models of malaria transmission were also not the first models for the transmission of an infectious disease. 
First was Bernoulli's model of smallpox, and P'Enko had published a model for flu a few years before. 
Ross was 


Our philosophy has been to design a framework for model building that can be used by programs. 
In this context, *model building* means designing ensembles of models. The next step involves applying a set of tools to computational tasks that are beyond what our brains could do. To accomplish our goals, we need more than the mathematical framework. We need to be able to implement and compute models. This requires new software. 

The software is structured around three major dynamical components and two interfaces. The dynamical components are: 1) the humans and malaria epidemiology, including the effects of treating malaria with drugs; 2) adult mosquito ecology, behavior and infection dynamics; and 3) aquatic mosquito ecology. Malaria transmission by mosquito populations, including the $2^{nd}$ and $3^{rd}$ dynamical component are set up to consider the effects of weather and vector control. The first interface links humans, adult mosquitoes, and parasites to describe parasite transmission through mosquito blood feeding and human exposure to infective mosquito populations. The second interface links adult and mosquito populations through egg laying and emergence. Within each component and interface, there are multiple sub-domains, and there are built in design features to deal with heterogeneity and other features for malaria control. After a 140 years of studying malaria, there's a lot of detail that could be important in some way. 
<!-- Part of what we need to do is sort through all that detail to find what is most relevant. -->

<!-- We have organized the concepts in this book around a narrative that allows us to introduce the core concepts -- those that make modular computation possible -- in an order that minimizes the need to draw on unfamiliar concepts. We start with the Ross-Maconald model, but our next task is to explain the new model for mosquito blood feeding.   -->

The software we have developed is meant to lower the costs of building and using models. We want programs to be focused on the decisions, the data, the concepts, and the analysis. As a metaphor, some students learn a numerical method for approximating $\sqrt{2}$ in school, but after learning it once, they stop worrying about *how* it is computed and they punch buttons into a calculator. Knowing how to compute something is sometimes useful, but worrying about how to compute it each time would interrupt the process that called for computing it. Instead, we punch the formula into a scientific calculator or any software that does computation confident that the machine knows how to do it. In applying models, the same kind of logic applies. People need to understand the concepts, but like a calculator, the tools should hide the technical details that don't add to a discussion. The software we have developed is a reliable interface for calculations designed to support policy. 

To learn how to use that software, we need to get through a lot of material. The background material in the following presentation is fairly sparse. We are trying to introduce just *enough* mathematics to teach users the critical concepts so they know what the software can do. We assume that the work will be done by teams that include a few people who understand the mathematics, who can guide others through the process. 

All of this sounds very complex, but we must start with something simple and layer on complexity in an ordered way. The first model we present is a Ross-Macdonald model. 

<!-- To fill in some of the gaps and technical, we have written (or can write) vignettes. On occasion, the text includes links to these vignettes for those who might find them useful. Please send suggestions about new vignettes to [smitdave@gmail.com](mailto:smitdave@gmail.com). -->

