# Malaria Metrics 

*The metrics commonly used in research and surveillence to measure malaria in populations.* 

*** 

If we want to manage malaria, we must be able to measure it. Models are approximations. We make a distinction between biological processes and observational processes. 

***

Note: in [Measuring Malaria for Control] we revisit the malaria metrics in the context of monitoring and evaluation for malaria control programs. Also see [@HaySI2008MeasuringMalaria] for a general overview of malaria metrics,  [@SmithDL2009MeasuringMalaria] and [@TustingLS2014MeasuringChanges]

## Malaria Epidemiology  

+ The duration of untreated malaria infections and the accuracy of various diagnostic methods in humans at different ages and with different histories of exposure;
+ The frequency of full and partial treatment with anti-malarial drugs overall; and especially the promptness of treatment in response to severe malaria;  

### Infection Prevalence

+ Spleen Rate

+ Parasite Rate 

### Infection Incidence 

+ Infection vs. Disease 

### Drug Taking 

### Disease 

+ The frequency of other causes of fever and disease and their interactions with malaria;  

### Serology  


## Mosquito Ecology 

### Entomological Inoculation Rates

+ HBR

+ SR 

+ EIR 

### Bionomics  

## Transmission 

### Infectiousness

### Vectorial Capacity  

### Transmission Efficiency

## Surveillance 

## Notes

[@HaySI2008MeasuringMalaria]
