# (PART) Epidemiology {-}

# Malaria Epidemiology

## Life Stages 

## Overview 

A major challenge for malaria dynamics is how to define an state space describing malaria infection and immunity in human populations that captures the essential elements of malaria dynamics well enough to trust for making policies. 
There are features of malaria infections that have been identified and studied in the past: superinfection; the complex time course of an infection -- including fluctuating parasite densities -- and the problem of detection; gametogenesis, gametocyte maturation and gametocyte dynamics; fever and disease; development of immunity with exposure including its effects on infection, disease, and infectiousness; treatment, adherence to drug regimens, chemoprotection and infection curing. Over time, these issues have been addressed in various models. 
We need model that is good enough for policy, but this also means developing a commmon understanding of malaria that can serve as a basis for discussion.  

To get to that point, we must start simple and add complexity. 

The model for malaria infection that we presented in [Malaria Dynamics] was developed by Ross. In today's vernacular, it would be called an SIS compartment model. The model is very simple, and it is probably inadequate for every task, but it is useful and it has been used. The model assumes that malaria infections clear at a constant rate regardless of the age of infection or other factors. The persistence of malaria infections over decades tells us that this assumption is clearly false, but it is good enough for some programmatic needs. During the GMEP, Ross's model was used to characterized the response timelines for the *Pf*PR after the interruption of transmission. Drawing on multiple sources, Macdonald estimated that the duration of infection was around 200 days, which was good enough to use as a basis for monitoring and evaluating the interruption of transmission  [@MacdonaldG1964MalariaParasite]. The simpler model was used even though Macdonald had already proposed an alternative model that considered superinfection [@MacdonaldG1950Superinfection]. Despite the simplicity, the model was adequate to the task [@SmithDL2009EndemicityResponse]. An important lesson is that the simplicity has some advantages, and the models that get used in policy tend to be very simple. 

The question is how to develop models that are simple and yet are up to policy tasks, which means that the models must (at some point) get validated against research data. Doing so means having sufficient complexity to deal with exposure, infection, detection, immunity, disease, infectiousness, care seeking, and drug taking. Whatever model is selected as a basis for policy, it should be simple enough to understand and yet complex enough to capture the *gist* of malaria epidemiology. The models, however chosen, must get it right. Sorting through all the complexity to get a model that is good enough is a daunting task. This introduction is mainly historical, but we use it to preview some of the themes. In the following history, we discuss some of the important innovations. 

## Infection 

### Superinfection 

From early on in malaria epidemiology it was clear that exposure to malaria differed among populations, and that in some places, the rate of exposure was far higher than the rate of clearance. Ross emphasized a need to measure exposure both entomologically, through metrics that are known today as the EIR and the FoI, and parasitologically, through the prevalence of infection by light microscopy (or more commonly today, through RDTs), which was called the malaria *parasite rate* . There was no good reason to believe that people in highly malarious areas would be exposed faster than they would clear infections, so they would carry infections that could be traced back to many infectious mosquitoes [@WaltonGA1947ControlMalaria]. This phenomenon was called superinfection.

Macdonald was the first to develop a mechanistic model of superinfection [@MacdonaldG1950Superinfection], but the mathematical formulation was at odds with his description [@FinePEM1975SuperinfectionProblem]. It is an interesting bit of history for a different time. 

A mathematical basis for understanding superinfection was worked out as a problem in the study of stochastic processes as part of *queueing theory.* This may seem strange, but understanding how many people are queueing involves understanding how people come in and how fast they are processed. One of these queuing models has become a mainstay of malaria epidemiology; in queuing theory, it is called $M/M/\infty$. 

The model tracks the **multiplicity of infection** (MoI). It assumes that infections arrive through exposure at a rate $h$ (the FoI), and that they clear independently. Without clearance, the MoI, denoted $\zeta$, would just go up. The model assumes that each infection clears at the rate $r$; if the MoI were $3$ then infections would clear at the rate $3r$. Regardless of how fast infections arrive, the fact that the pressure for the MOI to go down increases with MoI means that the MoI will reach a stable state. The mean MoI is $h/r.$ The following diagram illustrates and provides the equations: 

\begin{equation*}
\begin{array}{c}
%
\begin{array}{ccccccccc}
\zeta_0 &  {h\atop \longrightarrow} \atop {\longleftarrow \atop r} & \zeta_1  & {h\atop \longrightarrow} \atop {\longleftarrow \atop {2r}} & \zeta_2  & {h \atop \longrightarrow} \atop {\longleftarrow \atop {3r}} & \zeta_3  & {h \atop \longrightarrow} \atop {\longleftarrow \atop {4r}}& \ldots 
\end{array} 
\\ 
\\ 
\begin{array}{rl}
d\zeta_0/dt &= -h \zeta_0 + r \zeta_1 \\ 
d \zeta_i /dt &= -(h+r) \zeta_i + h \zeta_{i-1} + r(i+1) \zeta_{i+1} \\
\end{array} 
\end{array}
\end{equation*}

If one is willing to abandon compartment models, then it is possible to formulate more elegant solution using hybrid models. The mean MoI, $m$ changes according to the equation:

$$\frac{dm}{dt} = h - r m.$$
Using queuing models, it is easy to show that the distribution of the MoI is Poisson, and in these hybrid models, if the initial distribution is not Poisson, then it will converge to the Poisson distribution asymptotically. The complex dynamics of superinfection can thus be reduced to this simple equation.

Unfortunately, things become more complex if we add simple features such as treatment with drugs, or heterogeneous exposure. The distribution of the MoI is no longer Poisson [@HenryJM2020HybridModel]. Superinfection is an important part of malaria epidemiology, and we will use these models for superinfection in developing some adequate models for infection and immunity. 

In the Garki Model (see below), the waiting time to clear an infection used these queuing models to formulate an approximate clearance rate: $$ \frac{h}{e^{h/r}-1}$$

## Disease & Immunity 

The biggest failing of Ross's model, perhaps, was that it did not make any attempt to grapple with acquired immunity to malaria. It had always been clear that immunity to malaria was important because the prevalence of infection declined throughout adolescence and was consistently lower in adults, and because disease and severe disease were common in young children. The data accumulated through years of studying malaria, done as part of malaria therapy, provided supporting evidence for immunity. There was a difference in outcomes from being exposed to the same parasite (homologous challenge) compared with a different parasite (a heterologous challenge). Immunity had something to do with the number of different parasites that a person had seen. 

The first model to grapple with immunity was the Garki Model [@DietzK1974GarkiModel]. The main idea in the Garki Model was that it would be possible to understand malaria dynamics by expanding the number of compartments: the population was sub-divided into two non-immmune or semi-immune. Infection dynamics were tracked separately within each immune category: the infections would clear faster from semi-immune individuals, they were are not infectious, and they are less likely to test positive if they were infectious. Some features of the Garki model seem odd in retrospect: there were two infected states for non-immunes ($y_1$ and $y_2$), but only one for semi-immunes; there was no way to lose immunity; and the assumption that semi-immunes are not infectious. 

The Garki Model has had a poweful influence on malaria modeling. Several models since then have expanded on various themes. Several compartment models have been developed that replicate infection dynamics across immune stages: we call this *stage-structured immunity.* 

In the Garki Model, we can simulate the immuno-epidemiology of cohorts as they age. Eventually, the cohort *would* settle to an equilibrium. At that point, everyone is semi-immune,  a sizable fraction remains non-immune after a century. By the time the cohort reaches the steady state, everyone in the cohort has died. If we focus on the dynamics in the first two decades of life, prevalence rises as people become infected, and then it falls as people become semi-immune. The changing epidemiology as cohorts age is an important feature of malaria. In models like this, the concept of a *steady state* teaches us something, but the models draw attention to the sharp changes in malaria that occur throught the first 20 years of life. We can adapt the idea of  steady state to suit our needs -- under constant exposure, cohorts trace out *stable orbits* as they age. These stable orbits are a basis for understanding malaria dynamics *vs.* age. 

One application of these stable orbits is to understand the the relationship between age and infection prevalence as a function of exposure. Curiously, the Garki Model captures the basic shape of age-*Pf*PR curves, but it does not get the details right. When we start to look at the factors affecting the *Pf*PR by age in populations, we must acknowledge the need to add other features: drug taking and chemoprotection; differences in exposure that arise for a number of reasons; anemia, perhaps; seasonality. Not everything is about immuno-epidemiology. 

## Gametocytes and Infectiousness 

In Ross's models, everyone who is infected is also infectious. This is clearly wrong, but it may not be a terrible assumption under most circumstances. The Garki Model made the extreme assumption that semi-immune individuals are not infectious at all. There is now copious evidence that adults *do* transmit parasites to mosquitoes, but they are not as infectious. This decline in infectiousness occurs for two reasons: first, the densities of asexual-stage parasites in adults are controlled by immunity, so they are lower. Since a fraction of asexual parasites becomes gametocytes, the densities of gametocytes are also lower in adults.  Second, gametocyte densities are modulated by an immune response that affects malaria parasites in mosquitoes, which is called *gametocyte-stage transmission blocking* immunity. The dynamics of gametocyte-stage immunity change with age and exposure, and we will need to understand how this form of immunity waxes and wanes. 

There are some other important details about malaria infections that might be relevant in some contexts.  First, *P. falciparum* gametocytes take 8-12 days to mature. When combined with the 6 days in the liver, we must acknowledge that the latent period is at least 2 weeks. Because gametocytes must reach densities high enough to be transmitted, the effective latent period for humans is probably closer to 20 days. Since the parasites also need 10 days or more to mature in mosquitoes, the shortest parasite generations are probably at least a month long. 

Another feature of gametocytes that matters is that gametocyte populations are not always affected by anti-malarial drugs, so after taking drugs that clear all the asexual-stages, some people will remain infectious to mosquitoes for quite a while after being treated with some drugs. 

Ross's assumption may serve most needs, but the models must be good enough to guide policies, such as MDA or malaria elimination, when details about gametocytes and infectiousness can affect the outcomes of policies. 


## Treatment and Chemoprotection 

It is impossible to understand malaria infection dynamics without accounting for treatment with anti-malarial drugs and a brief period of chemo-protection that follows. The first model for drug treatment was developed to understand MDA [@DietzK1975ModelsParasitic]. In developing models for policy, we must be careful about drug taking and its effects because it modifies the relationship between exposure (the EIR) and infection. 

### The Time Course of an Infection

The time course of infections is complex, and we will need to develop some models that relate parasite densities. In the chapters that follow, we introduce two main kinds of models: 

+ AoI 

+ SoI 

### Intrahost Models 

There are two kinds of models we will discuss, but we would like to avoid them in making policy if possible.  

+ In host models; 

+ Individual-based models.  

### Synthesis

In the end, we do not need perfect models of malaria infection and immunity, but we do need a sound understanding of several things to make policy: 

+ The prevalence of infection by age as a function of exposure and drug-taking;   

    - ...in a cross-section of the population; 
    
    - ...in the care-seeking population.  

+ The incidence of malaria by severity and by age; 

+ The fraction of malaria that is promptly treated by severity and by age; 

+ The net infectiousness of a population of humans to mosquitoes. 

In the chapters that follow, we will develop some models that based on a new concept -- the age of the youngest infection -- that combine many of the ideas in the chapters above. 