# (PART) Transmission {-}

# Blood Feeding and Transmission

The endpoint  


### Search and Risk 

### Search Weights and Availability

To deal with heterogeneous exposure and many other phenomena, we need a sensible way of segmenting humans into population **strata**. Stratification makes it possible to deal with population heterogeneity. 

A new model of **blood feeding** is based on a model of blood feeding as the endpoint of a search for a blood host [@WuSL2023SpatialDynamics]. 

+ Each sub-population has a *search weight* ($w$), and the total *availability* of humans for blood feeding ($W$) is the sum of the sizes of the strata weighted by their search weights. 

+ We also consider the availability of alternative vertebrate species for blood feeding ($O$).


### Functional Response 

+ Mosquito blood feeding rates are computed using a *functional response* to total availability of vertebrate hosts ($f = F_f(B)$). 

+ To compute total availability, we add a scaling parameter on alternative hosts, because mosquito preferences can translate into different patterns of search; total availability is $B=W + O^\zeta$.  

+ The human fraction is proportional to the relative availability of hosts $q = W/B$. 

### Environmental Heterogeneity  

+ The *search weights* thus translate into a kind of **[Frailty]**, which is one component of *heterogeneous exposure.* Important sources of frailty include bednet use, housing type, and age. 

+ We also want to consider *variability* in exposure within a stratum -- what is the distribution of the *expected* number of bites over time? We have already discussed frailties, so this is a different kind of heterogeneous exposure that we call **[Environmental Heterogeneity]**.  This helps us to align models with data: mosquito counts data tend to be described well by *negative binomial* distributions, so it is likely that the distribution of infectious bites also follows a negative binomial distribution. We introduce a function that translate the EIR into the FoI: 
$$h=F_h(E)$$ 


In the Ross-Macdonald model, the underlying assumption is consistent with a Poisson distribution, but we have also derived *negative binomial hazard rates*. Environmental heterogeneity can arise from two sources: 

- the aggregated distributions of mosquitoes in micro-habitats, and the redistribution of mosquito populations by wind and weather; 
    
- random movements of humans around mosquito micro-habitats that affect their risk in a way that doesn't tend to change the mean; 


## Host Availability 

## Blood Feeding Rates 

## The Human Fraction 

## The Mixing Matrix, $\beta$ 